apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount # 권한을 부여할 대상이 ServiceAccount
  name: alicek106 # alicek106 서비스 어카운트에 권한 부여
  namespace: default
roleRef:
  kind: Role # Role 에 정의된 권한 부여
  name: service-reader # service-reader 라는 이름의 Role 대상(subject)에 연결
  apiGroup: rbac.authorization.k8s.io
