apiVersion: v1
kind: Service
metadata:
  name: hostname-svc-nodeport
spec:
  # externalTrafficPolicy: Local # 요청 전달 메커니즘, 로드 밸런스 정책.
  ports:
    - name: web-port
      port: 8080
      targetPort: 80
      # nodePort: 랜덤이 아님 지정 포트 사용
  selector:
    app: webserver
  type: NodePort # 노드 타입
  # 포드에 접근할 수 있는 포트를 클러스터의 모든 노드에 동일하게 개방. 따라서 외부에서 포드에 접근할 수 있는 서비스 타입.
  # 접근할 수 있는 포트는 랜덤으로 정해지지만, 특정 포트로 접근하도록 설정 가능