apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-nginx
spec:
  # 레플리카셋 정의
  replicas: 3 # 동일한 포드를 몇 개 유지시킬 것인지 설정
  selector:
    matchLabels: # 레플리카셋이 관리할 포드를 선택하기 위한 선택자(css 선택자와 비슷)
      app: my-nginx-pods-label # my-nginx-pods-label 리소스 관리함

  # 포드 정의
  template: # 포드를 생성할 때 사용할 템플릿 정의. 포드 스펙 또는 포드 템플릿이라고 말함.
    metadata: # 포드 리소스의 메타 데이터
      name: my-nginx-pod
      labels: # 선택자에 선택될 수 있는 레이블
        app: my-nginx-pods-label
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80