apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-nginx-pod
spec:
  replicas: 3
  selector:
      matchLabels:
        app: my-nginx-pod
  template:
    metadata:
      labels:
        app: my-nginx-pod
    spec:
      containers:
        - name: my-nginx-pod
          image: nginx:latest
          ports:
            - containerPort: 80
              protocol: TCP